    version: '3.3'
    services:
      wordpress:
        image: wordpress:latest
        restart: always
        links:
          - db:mysql
        ports:
          - "8001:80"
        working_dir: /var/www/html
        volumes:
          - "./html:/var/www/html/"
        environment:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: wordpress
      db:
        image: mysql:5.7
        restart: always
        volumes:
          - "./mysql:/var/lib/mysql"
        ports:
          - "3301:3306"
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
